#! /bin/bash
# /etc/init.d/bibbox
#

source /etc/bibbox/bibbox.cfg

updateexecute() {
  cd "$bibboxdir/$bibboxscriptfolder"
  chmod -R a+x "$bibboxdir/$bibboxscriptfolder"
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script BIBBOX "
    updateexecute
    source "$bibboxdir/$bibboxscriptfolder/initscripts/start.sh"
    ;;
  stop)
    echo "Stopping script BIBBOX"
    echo "Could do more yet"
    source "$bibboxdir/$bibboxscriptfolder/initscripts/stop.sh"
    ;;
  reload)
    echo "Reload script BIBBOX"
    updateexecute
    source "$bibboxdir/$bibboxscriptfolder/initscripts/reload.sh"
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop|reload}"
    exit 1
    ;;
esac

exit 0
