#! /bin/bash
### BEGIN INIT INFO
# Provides: bibbox
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: bibbox service
# Description: Start bibbox Service
### END INIT INFO

# /etc/init.d/bibbox
#

source /etc/bibbox/bibbox.cfg

updateexecute() {
  cd "$bibboxdir/$bibboxscriptfolder"
  chmod -R a+x "$bibboxdir/$bibboxscriptfolder"
}

# Carry out specific functions when asked to by the system
case "$1" in
  start)

    ;;
  stop)

    ;;
  reload)

    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop|reload}"
    exit 1
    ;;
esac

exit 0
